# Python Basics

### Variables:  
- Specific
- Case-sensitive name
- Call-up values through variable names   

In [1]:
message = "Hello World!"
print(message)

Hello World!


### Python Types:

- Standard Data Types: Numbers, String, List, Tuple, Dictionary
- Number type: int, long, float, complex

In [2]:
string = "Hello"
number = 1
list = [1, 2, 3]
dict = {"My":"dictionary"}

print(type(string))
print(type(number))
print(type(list))
print(type(dict))

<class 'str'>
<class 'int'>
<class 'list'>
<class 'dict'>


In [4]:
# Basic operations with same and different types 
# Several variables to experiment with
savings = 100
factor = 1.1
desc = "compound interest"

# Assigning product of factor and savings to year1
year1 = savings * factor

print(type(year1))

# Assigning sum of desc and desc to doubledesc
doubledesc = desc + desc

# Printing out doubledesc
print(doubledesc)

##Type conversion
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Converting pi_string into float: pi_float
pi_float = float(pi_string)

<class 'float'>
compound interestcompound interest
I started with $100 and now have $194.87171000000012. Awesome!


# Python Lists

- Name a collection of values
- Contain any type
- Contain different types

If you want to select a specific value in a list you should put the index of the value inside a square brackets after the list. You can use negative numbers as index too, it will start counting at the end of the list. (Lists in python starts at the index 0)

In [4]:
mylist = [1, 3, 5, 2, 3, 9]

print(mylist[0])

print(mylist[-1])

1
9


In [2]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapting list areas
areas = ["hallway", hall,"kitchen", kit, "living room", 
         liv,"bedroom", bed, "bathroom", bath]

# Printing areas
print (areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [3]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
         
print(house)
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


### List slicing
You can select more than only one value in a list using slicing. The first number will be the first index of the selection and the second number will be the index of the selection's end (the value in the second number index will not be part of the selection).

[ start(inclusive) : end(exclusive) ]

In [7]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

generic = areas[2:5]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)
print(generic)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]
['kitchen', 18.0, 'living room']


### Changing list elements
An value in a list can be added, deleted and updated. Variables with list type will point to a specific address in the memory. The variable does not save the values, it only point to the list location in the memory and this may cause some overwriting troubles. If you want to copy a list you should use the list() function, you will understand it better with the examples below.

In [11]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, 
         "bedroom", 10.75, "bathroom", 9.50]

# Change the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [14]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

print(areas_1)
print("\n")
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [16]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas, notice that the areas didn't change
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


# Functions and Packages

### Functions

Functions are a bunch of code that receive a input and (usually) display a output, also can be reused. Functions are useful to avoid repetitive code and repetitive work. We are already using a functions! The print() and type() function.

There are a lot of useful functions at the standard python package, some examples of useful functions are max(), round(), type(), print() and so on. Furthermore, the internet has a lot of useful functions that you can use in your own code.

Standard function call: function(parameters)

In [20]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
print(type(var2))
out2 = int(var2)
print(type(out2))

<class 'list'>
4
<class 'bool'>
<class 'int'>


In [21]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


### Methods

Methods are functions that belong to objects (object is the name of any type of saved data using variables in your code), the methods are directly connected with the type of the object. Each type has its own methods.

You can call methods usign a dot and the name of the method after the variable name: variable.method().

#### Functions VS Methods

Function: type(fam), it has a input and a output.

Method: list.index(someValue), it call functions *on* objects and can change the object's data.


In [23]:
# string to experiment with: room
room = "poolhouse"

# FUNCTION
# Use upper() on room: room_up
room_up = room.upper()

# Print out room and room_up
print(room)
print(room_up)

#METHOD
# Print out the number of o's in room
print(room.count("o"))

poolhouse
POOLHOUSE
3


In [25]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


### Packages

Packages are the directory of Python Scripts (module) and each script has functions, methods, types. Packages are useful to select only the necessary tools (methods and functions) to your project, avoiding adding a lot of useless code in your project.

There are thousands of packages over the world, some useful packages for Data Science are:
    - Numpy
    - Matplotlib
    - Scikit-learn
    
If you want to use a new package you should download and install it on your machine. After that you should import the package on your code, using the *import* command.

If you want to import only a single part of the package you should you the *from wantedPart import package*, you will understand it better with the examples below.

In [28]:
# Definition of radius
r = 0.43

# Import the math package
# Notice that if you import a whole package, you should define the
# the function or method using the name of the package dot the name
# of the function or method.
import math

# Calculate C
# math.pi is a variable inside the math package
C = 2 * math.pi * r

# Calculate A
A = math.pi * (r**2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [27]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
phi = radians(12)
dist = r * phi

# Print out dist
print(dist)

40317.10572106901


# NumPy

NumPy(Numeric Python) is a powerful package that can be used as a alternative to Python Lists. NumPy has a lot of useful functions, methods, variables and so on, it makes easier to work with linear algebra and vectorized data.

NumPy arrays contains only one type and different types of arrays has different behaviors with some commands, functions and methods.

Take a attention look at the examples below.

In [54]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

[180 215 210 210 188 176 209 200]


In [58]:
# Import a csv file with a huge data of soccer players
# We'll talk about pandas package and csv files later
import pandas as pd
players = pd.read_csv("Data\soccerPlayers.csv")

# Here starts the code with numpy
import numpy as np

# Select the height of the players and generate a numpy array
np_height = np.array(players['height_cm'])

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.01

# Print np_height_m
print(np_height_m)

[185. 170. 175. ... 175. 176. 182.]
[1.85 1.7  1.75 ... 1.75 1.76 1.82]


In [78]:
# Import a csv file with a huge data of soccer players
# We'll talk about pandas package and csv files later
import pandas as pd
players = pd.read_csv("Data\soccerPlayers.csv")

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(players['height_cm']) * 0.01

# Create array from weight
np_weight_kg = np.array(players['weight_kg'])

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)

# Print out bmi as String and use the \n to break the line
print(str(bmi) + '\n')

# Create the light array, it is boolean array
# True = value < 21 and False = value > 21
light = bmi < 21

# Print out light
print(str(light) + '\n')

# Print out BMIs of all baseball players whose BMI is below 21
print(str(bmi[light]) + '\n')

# Print out the weight at index 50
print(str(np_weight_kg[50]) + '\n')

# Print out sub-array of np_height: index 100 up to and including index 110
print(str(np_height_m[100:111]))

[23.37472608 24.91349481 22.20408163 ... 23.18367347 19.69266529
 21.73650525]

[False False False ... False  True False]

[20.4032323  20.75638717 20.97117202 ... 19.11075278 20.9370756
 19.69266529]

94.0

[1.73 1.87 1.81 1.95 1.92 1.89 1.84 1.82 1.94 1.86 1.69]


### 2D NumPy Arrays

First of all, if you're not familiarized with 2D arrays, think that arrays with more than 1 dimension are just list-of-lists.

Numpy arrays are N-dimensional, it means that a numpy array can have any size. The behavior of 2D arrays are similar to 1D arrays, however 2D has more possibilities of selection because its dimension. The examples below will show the possibilities.

In [77]:
# Import a csv file with a huge data of soccer players
# We'll talk about pandas package and csv files later
import pandas as pd
players = pd.read_csv("Data\soccerPlayers.csv")

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape (dimensions) of np_baseball
print(np_baseball.shape)

# Create a numpy array from players
np_players = np.array(players)

# Print out the shape of np_players
print(np_players.shape)

<class 'numpy.ndarray'>
(4, 2)
(17994, 185)


### NumPy: Basic Statistics

There is no sense if you have a lot of data but you can't understand and analyze it. When you are handling with thousands or millions of data, you will need to process the data to have a better understanding and statistics could help you.

Suppose you want to analyse the soccer players data that we use at the other examples and you want to know the mean and the median height of all players. Let's see how to do it with NumPy.

In [81]:
# Import a csv file with a huge data of soccer players
# We'll talk about pandas package and csv files later
import pandas as pd
players = pd.read_csv("Data\soccerPlayers.csv")

import numpy as np

# np_height_m receive the height in meters
np_height_m = np.array(players['height_cm']) * 0.01

# Print out the mean of np_height
print(np.mean(np_height_m))

# Print out the median of np_height
print(np.median(np_height_m))

1.8127197954873848
1.81


Now, you want to see how many players are bigger than the mean height.

In [85]:
# Import a csv file with a huge data of soccer players
# We'll talk about pandas package and csv files later
import pandas as pd
players = pd.read_csv("Data\soccerPlayers.csv")

import numpy as np

# np_height_m receive the height in meters
np_height_m = np.array(players['height_cm']) * 0.01

# np_mean receive the mean height
np_mean = np.mean(np_height_m)

# Generate a numpy boolean array with the heights biggers than the mean
np_bigger = np_height_m > np_mean

# Print the total number of players
print("Players total: " + str(np_height_m.shape))

# Print the number of players biggers than the mean
print("Players bigger than the mean: " +
      str(np.shape(np_height_m[np_bigger])))

Players total: (17994,)
Players bigger than the mean: (8856,)


Remember, this is a intro chapter so we will see more advanced statistics and analysis later on.